#!/bin/bash

# Author: Aron Chu
# Date created: 30/7/2021
# Last Modified 31/7/2021

# Description:
# Creates a backup in the users current directory of all files in
# the home directory

# Usage
# backup_script

echo "Hello, ${USER^}"
echo "I will now back up your home directory, $HOME"
currentdir=$(pwd)
echo "You are running in the script from $currentdir"
echo "Therefore, I will save the backup in $currentdir"
tar -cf $currentdir/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null
echo "Backup Completed Successfully"
exit 0

# Move into the directory with the script and grant
# execution priviliges using chmod +x backup_script
# To run it, use ./backup_script on a linux command line
